### ISSUE TITLE
cloud-translations is targeting Java 17

### ISSUE THREAD

**Issue by vlrjuan** [Incendo/cloud-translations#37]
It should target Java 8 as every other cloud modules

**Comment by Citymonstret** [comment]
We're using utilities not present in Java 8. The README now mentions the Java version requirement and we'll go over the wiki and clarify the Java version requirements for the different projects.

**Comment by jpenilla** [comment]
You can also use the published artifacts without using the contained code - the locale list & properties files are enough for you to write your own Java 8 loader.
